baseURL = "sgama.github.io"
buildDrafts = false
buildFuture = false
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
hideColorSchemeToggle = true
summaryLength = 0

[imaging]
anchor = "Center"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 100

[related]
indices = [{name = "tags", weight = 100}, {name = "categories", weight = 100}, {name = "series", weight = 50}, {name = "authors", weight = 20}, {name = "date", weight = 10}, {applyFilter = false, name = "fragmentrefs", type = "fragments", weight = 10}]
threshold = 0
toLower = false

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
