[hugoVersion]
    extended = false
    min = "0.87.0"
    
[[imports]]
    disable = false
    path = "github.com/martignoni/hugo-notice"
[[imports]]
    disable = false
    path = "github.com/nunocoracao/blowfish/v2"