autoSwitchAppearance = true
colorScheme = "catppuccin"
defaultAppearance = "dark"
# giteaDefaultServer = "https://git.fsfe.org"
# forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "background.jpg"
disableImageOptimization = false
disableTextInHeader = false
enableCodeCopy = true
enableSearch = true
highlightCurrentMenuArea = true
mainSections = ["posts"]
replyByEmail = false
smartTOC = true
smartTOCHideUnfocusedChildren = ""

[article]
editAppendPath = true
heroStyle = "background"
invertPagination = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
seriesOpened = false
showAuthor = false
showAuthorsBadges = false
showBreadcrumbs = true
showComments = false
showDate = true
showDateOnlyInArticle = false
showDateUpdated = false
showDraftLabel = true
showEdit = false
showHeadingAnchors = true
showHero = true
showLikes = false
showPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showViews = false
showWordCount = true
showZenMode = true

[footer]
showAppearanceSwitcher = false
showCopyright = true
showMenu = true
showScrollToTop = true
showThemeAttribution = true

[header]
layout = "fixed-fill-blur"

[homepage]
cardView = true
cardViewScreenWidth = false
disableHeroImageFilter = false  # only used when layout equals hero
layout = "custom"
layoutBackgroundBlur = true  # only used when layout equals background
showMoreLink = true
showMoreLinkDest = "/posts/"
# homepageImage = "background.jpg"
showRecent = true
showRecentItems = 3

[list]
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = true
groupByYear = false
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
orderByWeight = true
showBreadcrumbs = false
showCards = true
showHero = true
showLikes = false
showSummary = false
showTableOfContents = true
showViews = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
cardView = false
showBreadcrumbs = false
showHero = true
showLikes = false
showTableOfContents = true
showTermCount = true
showViews = false

[term]
cardView = ""
cardViewScreenWidth = false
groupByYear = false
showBreadcrumbs = false
showHero = true
showLikes = false
showTableOfContents = true
showViews = false
