version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Vancouver
    target-branch: develop
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: "chore(deps)"
      include: scope
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Vancouver
    target-branch: develop
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - go
      - hugo-theme
    commit-message:
      prefix: "chore(deps)"
      include: scope
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Vancouver
    target-branch: develop
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(ci)"
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
