language: generic
env:
  - HUGO_VERSION=0.36
addons:
  apt:
    packages:
    - python-pygments
before_script:
  - git submodule update --remote
  - curl --silent -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar zxf -
script:
  - GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD` ./hugo
after_success:
  - echo "samsongama.com" >> public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: develop

# language: go 
# go: 
#   - master # This uses automatically the latest version of go 
# install: 
#   - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI 
#   - pip install Pygments --user
# before_script: 
#   - curl --silent -L https://github.com/gohugoio/hugo/releases/download/v0.35/hugo_0.35_Linux-64bit.tar.gz | tar zxf - 
# script: 
#   - GIT_COMMIT_SHA=$(git rev-parse --verify HEAD)  
#   - GIT_COMMIT_SHA_SHORT=$(git rev-parse --short HEAD) 
#   - echo "$GIT_COMMIT_SHA_SHORT SHA $GIT_COMMIT_SHA" 
#   - hugo # This commands builds your website on travis 