baseURL = "https://samsongama.com/"
languageCode = "en"
title = "Samson Gama"
theme = "beautifulhugo"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
googleAnalytics = "UA-40665364-1"

[blackfriday]
    extensions = ["hardLineBreak"]

[Params]
    commit = "https://github.com/sgama/sg/tree/"
    subtitle = "Blog - WIP from Sept 16, Content incoming"
    logo = "img/nav-icon.jpg"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    rss = true
    comments = true
    readingTime = true
    gcse = "015123895069075366687:449fwtixz80"

[[Params.bigimg]]
 src = "img/sphere.jpg"
 desc = "Sphere"
 # position: see values of CSS background-position.
 position = "center top"

[Author]
    name = "Samson Gama"
    website = "https://samsongama.com"
    googleplus = "+SamsonGama"
    github = "sgama"
    gitlab = "sgama"
    bitbucket = "sgama"
    linkedin = "samsongama"
    spotify = "+sam"
    youtube = "samsongama"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "portfolio/"
    weight = 3

[[menu.main]]
    name = "Resume"
    url = "resume/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 5
