baseURL = "https://samsongama.com/"
languageCode = "en"
title = "Samson Gama"
theme = "beautifulhugo"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
googleAnalytics = "UA-40665364-1"

[blackfriday]
    extensions = ["hardLineBreak"]

[Params]
    commit = "https://github.com/sgama/sgama.github.io/tree/"
    subtitle = "Software Engineer (EIT)"
    logo = "img/nav-icon.jpg"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    rss = true
    comments = true
    readingTime = true

[Author]
    name = "Samson Gama"
    website = "https://samsongama.com"
    github = "sgama"
    linkedin = "samsongama"
    spotify = "+sam"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url = "portfolio"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "resume"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "contact"
    weight = 4
