services:
  lighthouse:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: lighthouse
    command: lhci autorun
    volumes:
      - ./public:/app/public
      - ./tests/lighthouserc.js:/app/lighthouserc.js
      - ./results:/app/results
